services:
  ssh1:
    build: .
    container_name: ssh1
    hostname: ssh1
    restart: unless-stopped
    ports:
      - "2222:22"

  ssh2:
    build: .
    container_name: ssh2
    hostname: ssh2
    restart: unless-stopped
    ports:
      - "2223:22"

  ssh3:
    build: .
    container_name: ssh3
    hostname: ssh3
    restart: unless-stopped
    ports:
      - "2224:22"
