---
- name: Remove old Docker installation
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: true
  become: true

- name: Install utils
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - apt-transport-https
      - software-properties-common
      - lsb-release
    update_cache: true
  become: true

- name: Import Docker gpg key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present
  become: true

- name: Get lsb_release
  ansible.builtin.command: lsb_release -cs
  register: lsb_release
  changed_when: false

- name: Set Docker repo base URL
  ansible.builtin.set_fact:
    docker_repo_base: >-
      {{ 'https://download.docker.com/linux/ubuntu' if ansible_facts['distribution'] | lower == 'ubuntu'
         else 'https://download.docker.com/linux/debian' }}

- name: Install docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ docker_repo_base }} {{ lsb_release.stdout }} stable"
    state: present
  become: true

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
    update_cache: true
  become: true
  notify: Restart docker

- name: Install docker-compose-plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
  become: true
  when: install_docker_compose | bool

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Launch docker (systemd)
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
  become: true
  when: ansible_service_mgr == 'systemd'

- name: Skip service start on non-systemd hosts
  ansible.builtin.debug:
    msg: "Service manager is {{ ansible_service_mgr }}; skipping docker service start."
  when: ansible_service_mgr != 'systemd'
