name: Check

on: 
  push:
    branches: [main, master]


jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CI/testApp
    steps:
      - name: Ceckout
        uses: actions/checkout@v6
        
      - name: reqs
        run: pip3 install -r requirements.txt

      - name: Linter
        run: flake8 .