name: Analize

on: 
  push:
    branches: [main, master]


jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CI/testApp
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: reqs
        run: pip3 install -r requirements.txt

      - name: Linter
        run: flake8 .

  test:
    needs: [lint]
    strategy:
      matrix:
        pyVersion: ['3.10', '3.12', '3.13']

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CI/testApp
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyVersion }}

      - name: reqs
        run: pip3 install -r requirements.txt

      - name: Test
        run: pytest

  security:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CI/testApp
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config auto .
